name = "Uncertain"
uuid = "b33f403f-199b-472b-b9d0-1cd2092892d0"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[weakdeps]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
IntervalSetsExt = "IntervalSets"
MakieExt = "Makie"
MeasurementsExt = "Measurements"
MonteCarloMeasurementsExt = "MonteCarloMeasurements"
UnitfulExt = "Unitful"

[compat]
Accessors = "0.1.39"
IntervalSets = "0.7"
Makie = "0.21.17"
Measurements = "2.11.0"
MonteCarloMeasurements = "1.2.1"
Unitful = "1.20.0"
julia = "1.10"
